### ISSUE TITLE
ボタンの色の移り変わりが遅い

### ISSUE THREAD

**Issue by jumang4423** [tom1236908745/masa_protfolio#1]
# ボタンの色の移り変わりが遅い

- ホームページのボタンの色のアニメーションが遅いので早くした方がいいと思います〜〜〜〜

**Comment by tom1236908745** [comment]
そんなことはない
# りょう◯んこ
## あ
- い
- う

**Comment by jumang4423** [comment]
![](https://media.giphy.com/media/3o7527pa7qs9kCG78A/giphy.gif)
